apiVersion: v1
kind: Service
metadata:
  name: {{ include "proglog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "proglog.labels" . | nindent 4 }}
spec:
  # Setting clusterIP to None creates a headless service. A headless service is the same
  # as default ClusterIP service, but lacks load balancing or proxying, allowing you to
  # connect to a Pod directly.
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: rpc
    port: {{ .Values.rpcPort }}
    targetPort: {{ .Values.rpcPort }}
  - name: serf-tcp
    protocol: "TCP"
    port: {{ .Values.serfPort }}
    targetPort: {{ .Values.serfPort }}
  - name: serf-udp
    protocol: "UDP"
    port: {{ .Values.serfPort }}
    targetPort: {{ .Values.serfPort }}
  selector: {{ include "proglog.selectorLabels" . | nindent 4 }}